---
- hosts: localhost
  gather_facts: yes
  pre_tasks:
    - name: Update all installed packages
      yum:
        name: '*'
        update_cache: yes
        state: latest
      tags: osupdate
  roles:
    - { role: epel-repo,     tags: core     }
    - { role: usermgmt,      tags: core     }
    - { role: sudo,          tags: core     }
    - { role: autoupdate,    tags: update   }
    - { role: ssh,           tags: ssh      }
    - { role: fail2ban,      tags: fail2ban }
    - { role: extra-tools,   tags: extra    }
    - { role: delosuser,     tags: osuser   }

