---
- hosts: localhost
  gather_facts: yes
  roles:
    - { role: epel-repo,          tags: [ "core", "epel-repo" ] }
    - { role: osupdate,           tags: [ "never", "osupdate" ] }
    - { role: usermgmt,           tags: [ "core", "usermgmt"  ] }
    - { role: sudo,               tags: [ "core", "sudo"      ] }
    - { role: autoupdate-rhel,    tags: autoupdate,             when: ansible_os_family == "RedHat" }
    - { role: autoupdate-debian,  tags: autoupdate,             when: ansible_os_family == "Debian" }
    - { role: ssh,                tags: ssh                     }
    - { role: fail2ban,           tags: fail2ban                }
    - { role: extra-tools,        tags: extra-tools             }
    - { role: delclouduser,       tags: delclouduser            }
    - { role: cron,               tags: [ "never", "cron"     ] }
