---
- hosts: login
  connection: local
  become: true

  tasks:
    - include_vars:
        file: users/user_defs.yml
        name: user_defs

    - debug:
        msg: '{{ user_defs.users }}'

    - name: Setup Users
      user:
        name: '{{ item.username }}'
        state: '{{ item.state | default("present") }}'
        remove: true
        shell: '{{ item.shell | default("/sbin/nologin") }}'
        groups: '{{ item.group | default("") }}'
        append: true
      with_items: '{{ user_defs.users }}'
      loop_control:
        label: '{{ item.username }}'

    - name: Setup SSH Keys
      authorized_key:
        manage_dir: yes
        state: present
        exclusive: yes
        user: '{{ item.username }}'
        key: "{{ lookup('pipe','cat users/{{ item.username }}/*.pub') }}"
      with_items: '{{ user_defs.users }}'
      when: ( item.state != "absent" )
      loop_control:
        label: '{{ item.username }}'

    - name: Add Admin Group to Sudoers
      lineinfile:
        dest: /etc/sudoers
        regexp: "^%{{ user_defs.group_core }}"
        line: "%{{ user_defs.group_core }} ALL=(ALL) NOPASSWD:ALL"

    - name: Disable Requiretty from sudoers
      lineinfile:
        dest: /etc/sudoers
        regexp: "Defaults    requiretty"
        line: "#Defaults    requiretty"
