---
- name: Install fail2ban
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - fail2ban

- name: Start fail2ban service
  service:
    name: fail2ban
    state: started
    enabled: yes

