---
- name: Update all installed packages
  yum:
    name: '*'
    update_cache: yes
    state: latest
  when:
    - ansible_os_family == "RedHat"
 
 - name: Update all installed packages
  apt:
    name: '*'
    update_cache: yes
    state: latest
  when:
    - ansible_os_family == "Debian"
 